name: Code Quality
on:
  pull_request:
  push:
permissions: {}
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run ESLint
        run: bun run lint
      - name: Run Prettier
        run: bun run format
      - uses: autofix-ci/action@v1
        with:
          commit-message: "style: apply ESLint and Prettier formatting"